# Generated by Django 5.1.3 on 2025-01-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
