# Generated by Django 5.1.3 on 2025-01-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_module.citymodel', verbose_name='شهر'),
        ),
    ]
