# Generated by Django 5.1.3 on 2025-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0008_alter_citymodel_options_remove_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='تصویر'),
        ),
    ]
