# Generated by Django 5.1.3 on 2025-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0010_user_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد پستی'),
        ),
    ]
