# Generated by Django 5.1.3 on 2024-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_categorymodel_alter_brandmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/product_img/'),
        ),
    ]
