# Generated by Django 5.1.3 on 2025-01-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productsummerymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSummeryModel',
        ),
    ]
