# Generated by Django 5.1.3 on 2025-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_delete_productsummerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
    ]
