# Generated by Django 5.1.3 on 2025-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_productmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='number',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
