# Generated by Django 5.1.3 on 2024-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomodel',
            name='image',
            field=models.ImageField(upload_to='./logo'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='./slider'),
        ),
    ]
