# Generated by Django 5.1.3 on 2024-12-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting_module', '0003_logomodel_is_active_slidermodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک ها',
            },
        ),
        migrations.AlterModelOptions(
            name='logomodel',
            options={'verbose_name': 'لوگو', 'verbose_name_plural': 'لوگو ها'},
        ),
        migrations.AlterModelOptions(
            name='slidermodel',
            options={'verbose_name': 'پوستر', 'verbose_name_plural': 'پوستر ها'},
        ),
        migrations.AlterField(
            model_name='logomodel',
            name='image',
            field=models.ImageField(upload_to='./logo', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='logomodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='./slider', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
