# Generated by Django 5.1.3 on 2024-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting_module', '0004_linkmodel_alter_logomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.CharField(max_length=300, verbose_name='لینک'),
        ),
    ]
