# Generated by Django 5.1.3 on 2024-12-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting_module', '0005_alter_linkmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان'),
        ),
    ]
