# Generated by Django 5.1.3 on 2025-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting_module', '0006_linkmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='link', verbose_name='تصویر'),
        ),
    ]
