# Generated by Django 5.1.3 on 2025-01-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0001_initial'),
        ('product_module', '0008_productmodel_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={'verbose_name': 'فاکتور کاربر', 'verbose_name_plural': 'فاکتور های کاربران'},
        ),
        migrations.CreateModel(
            name='InvoiceProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_module.productmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'فاکتور محصولات',
                'verbose_name_plural': 'فاکتور محصولات',
            },
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='products',
            field=models.ManyToManyField(to='cart_module.invoiceproductmodel', verbose_name='محصولات'),
        ),
    ]
