# Generated by Django 5.1.3 on 2025-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0002_alter_invoicemodel_options_invoiceproductmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproductmodel',
            options={'verbose_name': 'فاکتور محصولات', 'verbose_name_plural': 'فاکتور های محصولات'},
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخته شده در'),
        ),
        migrations.AddField(
            model_name='invoiceproductmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ساخته شده در'),
        ),
    ]
