# Generated by Django 5.1.3 on 2025-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0003_alter_invoiceproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='invoiceproductmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در'),
        ),
    ]
