# Generated by Django 5.1.3 on 2024-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_remove_contactmodel_user_contactmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='شماره تماس'),
        ),
    ]
