# Generated by Django 5.1.3 on 2024-12-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_alter_blogmodel_date_alter_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
