# Generated by Django 5.1.3 on 2025-01-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_alter_blogmodel_user_alter_commentmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogmodel', verbose_name='مقاله'),
        ),
    ]
