# Generated by Django 5.1.3 on 2025-01-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_commentmodel_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogmodel', verbose_name='مقاله'),
        ),
    ]
